import io
from datetime import datetime, timezone
from fpdf import FPDF
from fpdf.enums import XPos, YPos


def clean_pdf_text(text: str | None) -> str:
    if not text:
        return ""
    replacements = {
        "\u201c": '"', "\u201d": '"', "\u2018": "'", "\u2019": "'",
        "\u2013": "-", "\u2014": "--", "\u2026": "...", "\u2022": "*",
    }
    for k, v in replacements.items():
        text = text.replace(k, v)
    return text.encode("latin-1", errors="replace").decode("latin-1")


class CyberCortexPDF(FPDF):
    """
    Subclass of FPDF to provide clean, customized headers, footers, and design layouts.
    """

    def header(self):
        # We suppress running headers on the cover page (Page 1)
        if self.page_no() > 1:
            self.set_font("helvetica", "B", 8)
            self.set_text_color(156, 163, 175)  # Gray text
            self.cell(0, 10, "CYBERCORTEX - SECURITY ASSESSMENT REPORT", border=0, align="L")
            self.set_font("helvetica", "", 8)
            self.cell(0, 10, f"Page {self.page_no()}", border=0, align="R")
            self.ln(10)

            # Draw a sleek violet separator line
            self.set_draw_color(139, 92, 246)  # Purple Accent
            self.set_line_width(0.5)
            self.line(10, 18, 200, 18)
            self.ln(5)

    def footer(self):
        if self.page_no() > 1:
            self.set_y(-15)
            self.set_font("helvetica", "I", 8)
            self.set_text_color(156, 163, 175)
            self.cell(
                0,
                10,
                "CONFIDENTIAL - Generated by CyberCortex. Authorized access only.",
                border=0,
                align="C",
            )


def generate_pdf_report(scan, findings: list, mode: str = "technical") -> bytes:
    """
    Generate a professional multi-page PDF security report and return it as bytes.
    Supports "technical" (full detail) and "executive" (exec_summary only, top 3, no jargon).
    """
    # Create the PDF context
    pdf = CyberCortexPDF(orientation="P", unit="mm", format="A4")
    pdf.mode = mode
    pdf.set_auto_page_break(auto=True, margin=20)

    # ----------------------------------------------------
    # PAGE 1: COVER PAGE
    # ----------------------------------------------------
    pdf.add_page()
    pdf.set_font("helvetica", "B", 26)
    pdf.set_text_color(31, 41, 55)  # Dark gray
    pdf.ln(25)
    pdf.cell(0, 12, "CYBERGUARDIAN AI", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="L")

    pdf.set_font("helvetica", "B", 13)
    pdf.set_text_color(139, 92, 246)  # Purple Accent
    report_subtitle = (
        "Executive Security Vulnerability Summary"
        if mode == "executive"
        else "Automated Security Assessment & Threat Remediation Guide"
    )
    pdf.cell(0, 8, report_subtitle, new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="L")
    pdf.ln(15)

    # Divider line
    pdf.set_draw_color(229, 231, 235)
    pdf.set_line_width(1)
    pdf.line(10, 62, 200, 62)
    pdf.ln(10)

    # Metadata Panel (Target info, dates, etc.)
    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(75, 85, 99)

    pdf.cell(40, 8, "Target Hostname:", border=0)
    pdf.set_font("helvetica", "B", 10)
    domain_name = clean_pdf_text(scan.asset.domain) if (scan.asset and scan.asset.domain) else "Unknown"
    pdf.cell(0, 8, domain_name, border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(75, 85, 99)
    pdf.cell(40, 8, "Scan Job Identifier:", border=0)
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 8, str(scan.id), border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(75, 85, 99)
    pdf.cell(40, 8, "Date of Audit:", border=0)
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(17, 24, 39)
    date_str = (scan.completed_at or datetime.now(timezone.utc)).strftime("%B %d, %Y - %H:%M UTC")
    pdf.cell(0, 8, date_str, border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(75, 85, 99)
    pdf.cell(40, 8, "Assessment Type:", border=0)
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(17, 24, 39)
    report_type_desc = (
        "Executive Risk Overview (Non-Technical)"
        if mode == "executive"
        else "Hybrid Passive & Light Active Security Scan"
    )
    pdf.cell(0, 8, report_type_desc, border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(15)

    # Risk Index Callout box (Color determined by risk_score)
    score = scan.risk_score if scan.risk_score is not None else 100
    if score >= 85:
        box_bg = (209, 250, 229)    # Light Green
        text_color = (6, 95, 70)    # Green
        status_label = "SECURE"
    elif score >= 70:
        box_bg = (254, 243, 199)    # Light Orange
        text_color = (146, 64, 14)   # Orange
        status_label = "WARNING"
    else:
        box_bg = (254, 226, 226)    # Light Red
        text_color = (153, 27, 27)   # Red
        status_label = "DANGER"

    pdf.set_fill_color(*box_bg)
    pdf.set_draw_color(*text_color)
    pdf.set_line_width(0.5)
    pdf.rect(10, 115, 180, 32, style="DF")

    pdf.set_xy(15, 120)
    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(*text_color)
    pdf.cell(100, 6, "WORKSPACE RISK INDEX", border=0)
    pdf.set_font("helvetica", "B", 24)
    pdf.cell(70, 20, f"{score} / 100", border=0, align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_xy(15, 126)
    pdf.set_font("helvetica", "B", 10)
    pdf.set_text_color(*text_color)
    pdf.cell(100, 6, f"Status: {status_label}", border=0)
    pdf.ln(30)

    # Disclaimer note at footer of page 1
    pdf.set_y(-30)
    pdf.set_font("helvetica", "", 8)
    pdf.set_text_color(156, 163, 175)
    disclaimer = (
        "Notice: CyberCortex assessment reports are proprietary, confidential safety summaries. "
        "All scanning tasks were configured and executed strictly under domains ownership verification. "
        "Remediation steps are suggestions based on best practices and default scanner templates."
    )
    pdf.multi_cell(0, 4, disclaimer, border=0, align="L")

    # Filter findings: ignore false_positive or accepted_risk for the general score summary count
    active_findings = [f for f in findings if f.status == "open"]

    severity_order = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
    sorted_findings = sorted(active_findings, key=lambda f: severity_order.get(f.severity.lower(), 5))

    # ----------------------------------------------------
    # EXECUTIVE MODE
    # ----------------------------------------------------
    if mode == "executive":
        pdf.add_page()
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(0, 10, "1. Executive Vulnerability Summary", border=0, ln=True)
        pdf.ln(2)

        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(55, 65, 81)
        exec_summary_desc = (
            f"CyberCortex performed an executive-level security review of the target domain '{scan.asset.domain}'. "
            f"The scanner identified {len(active_findings)} outstanding security issues. "
            "This report summarizes the top 3 issues impacting your security posture. "
            "These findings do not include technical coding terminology or raw packet headers, allowing business stakeholders "
            "to understand operational risk factors easily."
        )
        pdf.multi_cell(0, 5, exec_summary_desc, border=0)
        pdf.ln(10)

        pdf.set_font("helvetica", "B", 12)
        pdf.set_text_color(139, 92, 246)
        pdf.cell(0, 8, "Top 3 Key Issues & Business Posture Impact", border=0, ln=True)
        pdf.ln(4)

        top_3 = sorted_findings[:3]
        if not top_3:
            pdf.set_font("helvetica", "I", 10)
            pdf.set_text_color(107, 114, 128)
            pdf.cell(0, 8, "No active security vulnerabilities were identified.", border=0, ln=True)
        else:
            for idx, f in enumerate(top_3):
                # Clean Callout Box for each finding
                pdf.set_draw_color(229, 231, 235)
                pdf.set_fill_color(249, 250, 251)
                pdf.set_line_width(0.3)
                
                # Draw box envelope dynamically
                x, y_start = pdf.get_x(), pdf.get_y()
                pdf.set_xy(x, y_start + 2)
                
                # Severity Color-Coding
                sev_lower = f.severity.lower()
                if sev_lower == "critical":
                    col = "Critical"
                    col_code = (153, 27, 27)
                elif sev_lower == "high":
                    col = "High"
                    col_code = (146, 64, 14)
                elif sev_lower == "medium":
                    col = "Medium"
                    col_code = (30, 64, 175)
                else:
                    col = f.severity.title()
                    col_code = (75, 85, 99)

                pdf.set_font("helvetica", "B", 11)
                pdf.set_text_color(17, 24, 39)
                pdf.cell(140, 7, f" {idx+1}. {f.title}", border=0)
                
                pdf.set_text_color(*col_code)
                pdf.set_font("helvetica", "B", 9)
                pdf.cell(0, 7, f" {col.upper()} RISK", border=0, align="R", ln=True)
                
                pdf.set_font("helvetica", "", 10)
                pdf.set_text_color(75, 85, 99)
                pdf.cell(0, 6, f"  Category: {f.category.title()}", border=0, ln=True)
                
                pdf.set_font("helvetica", "", 10)
                pdf.set_text_color(55, 65, 81)
                summary_string = f.exec_summary or f.description or "No executive summary compiled."
                pdf.multi_cell(0, 5, f"  Impact: {summary_string}", border=0)
                pdf.ln(8)

        # Save and return bytes
        buffer = io.BytesIO()
        pdf.output(buffer)
        return buffer.getvalue()

    # ----------------------------------------------------
    # PAGE 2: TECHNICAL MODE EXECUTIVE SUMMARY
    # ----------------------------------------------------
    pdf.add_page()
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 10, "1. Executive Summary", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    # Count counts
    critical_c = sum(1 for f in findings if f.severity.lower() == "critical" and f.status == "open")
    high_c = sum(1 for f in findings if f.severity.lower() == "high" and f.status == "open")
    medium_c = sum(1 for f in findings if f.severity.lower() == "medium" and f.status == "open")
    low_c = sum(1 for f in findings if f.severity.lower() == "low" and f.status == "open")
    info_c = sum(1 for f in findings if f.severity.lower() == "info" and f.status == "open")

    pdf.set_font("helvetica", "", 10)
    pdf.set_text_color(55, 65, 81)
    summary_text = (
        f"CyberCortex executed a security audit on domain '{scan.asset.domain}'. "
        f"The scanning engine identified a total of {len(active_findings)} active vulnerabilities. "
        f"Breakdown of issues: {critical_c} Critical, {high_c} High, {medium_c} Medium, {low_c} Low, and {info_c} Info findings.\n\n"
        "Below is the complete findings index detailing each issue. Step-by-step code remediation "
        "details are provided in Section 2 of this report."
    )
    pdf.multi_cell(0, 5, summary_text, border=0)
    pdf.ln(10)

    pdf.set_font("helvetica", "B", 12)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 8, "Findings Matrix Index", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(2)

    # Findings Table
    # Table headers: Title (85mm), Severity (35mm), Category (35mm), CVSS (25mm) -> Total 180mm
    pdf.set_font("helvetica", "B", 9)
    pdf.set_fill_color(243, 244, 246)  # Gray header bg
    pdf.set_text_color(55, 65, 81)
    pdf.cell(85, 8, " Finding Title", border=1, fill=True)
    pdf.cell(35, 8, " Severity", border=1, fill=True)
    pdf.cell(35, 8, " Category", border=1, fill=True)
    pdf.cell(25, 8, " CVSS Score", border=1, fill=True, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("helvetica", "", 9)
    pdf.set_text_color(17, 24, 39)

    for idx, f in enumerate(sorted_findings):
        # Color coding for severity cell background
        sev_lower = f.severity.lower()
        if sev_lower == "critical":
            sev_bg = (254, 226, 226)
            sev_text = (153, 27, 27)
        elif sev_lower == "high":
            sev_bg = (254, 243, 199)
            sev_text = (146, 64, 14)
        elif sev_lower == "medium":
            sev_bg = (219, 234, 254)
            sev_text = (30, 64, 175)
        elif sev_lower == "low":
            sev_bg = (207, 250, 254)
            sev_text = (21, 94, 117)
        else:
            sev_bg = (243, 244, 246)
            sev_text = (75, 85, 99)

        # Title Cell (auto wrap support if title is long)
        pdf.cell(85, 8, f" {f.title[:45]}", border=1)

        # Severity Cell with custom background
        pdf.set_fill_color(*sev_bg)
        pdf.set_text_color(*sev_text)
        pdf.set_font("helvetica", "B", 9)
        pdf.cell(35, 8, f"  {f.severity.upper()}", border=1, fill=True)

        # Reset text colors for other cells
        pdf.set_text_color(17, 24, 39)
        pdf.set_font("helvetica", "", 9)
        pdf.cell(35, 8, f"  {f.category.title()}", border=1)
        
        cvss_val = f"{f.cvss_score}" if f.cvss_score is not None else "--"
        pdf.cell(25, 8, cvss_val, border=1, align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ----------------------------------------------------
    # PAGE 3+: VULNERABILITY DETAILS SECTION (TECHNICAL ONLY)
    # ----------------------------------------------------
    for idx, f in enumerate(sorted_findings):
        f_title = clean_pdf_text(f.title)
        f_desc = clean_pdf_text(f.description or "No description provided.")
        f_rem = clean_pdf_text(f.remediation or "No remediation steps specified.")
        f_cat = clean_pdf_text(f.category.title() if f.category else "General")

        pdf.add_page()
        pdf.set_font("helvetica", "B", 14)
        pdf.set_text_color(139, 92, 246)  # Purple Accent
        pdf.cell(0, 10, f"2.{idx+1} {f_title}", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(2)

        # Metadata table list
        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(75, 85, 99)
        pdf.cell(30, 6, "Severity:", border=0)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(60, 6, f.severity.upper() if f.severity else "INFO", border=0)

        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(75, 85, 99)
        pdf.cell(30, 6, "Category:", border=0)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(0, 6, f_cat, border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(75, 85, 99)
        pdf.cell(30, 6, "CVSS v3 Score:", border=0)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(60, 6, str(f.cvss_score or "N/A"), border=0)

        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(75, 85, 99)
        pdf.cell(30, 6, "OWASP Top 10:", border=0)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(0, 6, clean_pdf_text(f.owasp_mapping or "None"), border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.set_font("helvetica", "B", 9)
        pdf.set_text_color(75, 85, 99)
        pdf.cell(30, 6, "MITRE ATT&CK:", border=0)
        pdf.set_font("helvetica", "", 9)
        pdf.set_text_color(17, 24, 39)
        pdf.cell(0, 6, clean_pdf_text(f.mitre_mapping or "None"), border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(5)

        # Sleek line separating metadata from description
        pdf.set_draw_color(243, 244, 246)
        pdf.set_line_width(0.5)
        pdf.line(10, 48, 200, 48)
        pdf.ln(5)

        # Vulnerability Risk Description
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(31, 41, 55)
        pdf.cell(0, 6, "Risk Explanation & Impact:", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(1)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(55, 65, 81)
        pdf.multi_cell(0, 5, f_desc)
        pdf.ln(6)

        # Remediation & Action Plan
        pdf.set_font("helvetica", "B", 10)
        pdf.set_text_color(31, 41, 55)
        pdf.cell(0, 6, "Remediation & Action Plan:", border=0, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        pdf.ln(1)
        pdf.set_font("helvetica", "", 10)
        pdf.set_text_color(55, 65, 81)
        pdf.multi_cell(0, 5, f_rem)

    # Save to dynamic buffer and return binary data stream
    buffer = io.BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()
