"""add_dashboard_and_drift_columns

Revision ID: 85874397d3ad
Revises: 
Create Date: 2026-08-18 15:54:10.701137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85874397d3ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('github_repo', sa.String(), nullable=True))
    op.add_column('assets', sa.Column('github_token', sa.String(), nullable=True))
    op.add_column('findings', sa.Column('ai_explanation', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('exec_summary', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('status', sa.String(), nullable=False))
    op.add_column('findings', sa.Column('status_note', sa.Text(), nullable=True))
    op.add_column('findings', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('findings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('findings', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('findings', 'remediation',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('findings', 'raw_output',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=True)
    op.add_column('scans', sa.Column('status_detail', sa.Text(), nullable=True))
    op.alter_column('scans', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scans', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('scans', 'status_detail')
    op.alter_column('findings', 'raw_output',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('findings', 'remediation',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('findings', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('findings', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('findings', 'created_at')
    op.drop_column('findings', 'status_note')
    op.drop_column('findings', 'status')
    op.drop_column('findings', 'exec_summary')
    op.drop_column('findings', 'ai_explanation')
    op.drop_column('assets', 'github_token')
    op.drop_column('assets', 'github_repo')
    # ### end Alembic commands ###
