"""add_ci_token_alerts_and_otp

Revision ID: c0041e898005
Revises: e39683889b65
Create Date: 2026-08-18 17:57:39.037121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0041e898005'
down_revision: Union[str, None] = 'e39683889b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('ci_token', sa.String(), nullable=True))
    op.add_column('identity_checks', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    op.add_column('organizations', sa.Column('notification_channels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'notification_channels')
    op.drop_column('identity_checks', 'otp_expires_at')
    op.drop_column('assets', 'ci_token')
    # ### end Alembic commands ###
